# Generated by Django 3.2.21 on 2023-09-24 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='posts',
        ),
    ]
